<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="51ea299ac8e0" name="TestExample" tests="2" failures="2" timestamp="29 Mar 2018 12:34:28 GMT" time="0.014" errors="0">
  <testcase name="test1" time="0.013" classname="TestExample">
    <failure type="java.lang.AssertionError" message="expected:&lt;12&gt; but was:&lt;1&gt;">
      <![CDATA[java.lang.AssertionError: expected:<12> but was:<1>at org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)at TestExample.test1(TestExample.scala:10)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)at java.util.concurrent.FutureTask.run(FutureTask.java:266)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="TestExample">
    <failure type="java.lang.AssertionError" message="expected:&lt;12&gt; but was:&lt;1&gt;">
      <![CDATA[java.lang.AssertionError: expected:<12> but was:<1>at org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)at TestExample.test1(TestExample.scala:10)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)at java.util.concurrent.FutureTask.run(FutureTask.java:266)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- TestExample -->
